### ISSUE TITLE
Source of the MOD11 definition?

### ISSUE THREAD

**Issue by fatso83** [Tieske/mod11#1]
I was using the [Norwegian MOD11 page](https://no.wikipedia.org/wiki/MOD11) as a source for my MOD11 code, but it turned out to be wrong, and the references were circular.

So I could find no definitive reference on how MOD11 was supposed to be implemented. Could you add such a definition to your project? There might be several MOD11 definitions for all I know.

**Comment by Tieske** [comment]
There are multiple ways of calculating the numbers. Just make sure you calculate them in the same way that you verify them.

try these;
- http://www.eclectica.ca/howto/modulus-11-self-check.php
- http://www.loc.gov/issn/check.html
- http://www.pgrocer.net/Cis51/mod11.html
